src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $created_art;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Author_IP;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nb_view;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedArt(): ?\DateTimeInterface
    {
        return $this->created_art;
    }

    public function setCreatedArt(?\DateTimeInterface $created_art): self
    {
        $this->created_art = $created_art;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(?string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }

    public function getAuthorIP(): ?string
    {
        return $this->Author_IP;
    }

    public function setAuthorIP(?string $Author_IP): self
    {
        $this->Author_IP = $Author_IP;

        return $this;
    }

    public function getNbView(): ?string
    {
        return $this->nb_view;
    }

    public function setNbView(?string $nb_view): self
    {
        $this->nb_view = $nb_view;

        return $this;
    }
}

src/Entity/Title.php
<?php

namespace App\Entity;

use App\Repository\TitleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TitleRepository::class)
 */
class Title
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $created_art;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nb_views;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $create_ip;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(?string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedArt(): ?\DateTimeInterface
    {
        return $this->created_art;
    }

    public function setCreatedArt(?\DateTimeInterface $created_art): self
    {
        $this->created_art = $created_art;

        return $this;
    }

    public function getNbViews(): ?string
    {
        return $this->nb_views;
    }

    public function setNbViews(?string $nb_views): self
    {
        $this->nb_views = $nb_views;

        return $this;
    }

    public function getCreateIp(): ?string
    {
        return $this->create_ip;
    }

    public function setCreateIp(?string $create_ip): self
    {
        $this->create_ip = $create_ip;

        return $this;
    }
}

src/Controller/ArticleCrudController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\Article1Type;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/article/crud')]
class ArticleCrudController extends AbstractController
{
    #[Route('/', name: 'article_crud_index', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article_crud/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'article_crud_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $article = new Article();
        $form = $this->createForm(Article1Type::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article_crud/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'article_crud_show', methods: ['GET'])]
    public function show(Article $article): Response
    {
        return $this->render('article_crud/show.html.twig', [
            'article' => $article,
        ]);
    }

    #[Route('/{id}/edit', name: 'article_crud_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Article1Type::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('article_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article_crud/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'article_crud_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('article_crud_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article_crud/_delete_form.html.twig
<form method="post" action="{{ path('article_crud_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article_crud/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/article_crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('article_crud/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('article_crud_index') }}">back to list</a>

    {{ include('article_crud/_delete_form.html.twig') }}
{% endblock %}

templates/article_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <h1>Article index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Content</th>
                <th>Created_art</th>
                <th>Slug</th>
                <th>Author_IP</th>
                <th>Nb_view</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.content }}</td>
                <td>{{ article.createdArt ? article.createdArt|date('Y-m-d') : '' }}</td>
                <td>{{ article.Slug }}</td>
                <td>{{ article.AuthorIP }}</td>
                <td>{{ article.nbView }}</td>
                <td>
                    <a href="{{ path('article_crud_show', {'id': article.id}) }}">show</a>
                    <a href="{{ path('article_crud_edit', {'id': article.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('article_crud_new') }}">Create new</a>
{% endblock %}

templates/article_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <h1>Create new Article</h1>

    {{ include('article_crud/_form.html.twig') }}

    <a href="{{ path('article_crud_index') }}">back to list</a>
{% endblock %}

templates/article_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>Article</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ article.title }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ article.content }}</td>
            </tr>
            <tr>
                <th>Created_art</th>
                <td>{{ article.createdArt ? article.createdArt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ article.Slug }}</td>
            </tr>
            <tr>
                <th>Author_IP</th>
                <td>{{ article.AuthorIP }}</td>
            </tr>
            <tr>
                <th>Nb_view</th>
                <td>{{ article.nbView }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('article_crud_index') }}">back to list</a>

    <a href="{{ path('article_crud_edit', {'id': article.id}) }}">edit</a>

    {{ include('article_crud/_delete_form.html.twig') }}
{% endblock %}